const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("zenithDesktop", {
  selectFolder: () => ipcRenderer.invoke("zenith:select-folder"),
  readDirectory: (directoryPath) => ipcRenderer.invoke("zenith:read-directory", directoryPath),
  closeWorkspace: () => ipcRenderer.invoke("zenith:close-folder"),
  readFile: (filePath) => ipcRenderer.invoke("zenith:read-file", filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke("zenith:write-file", filePath, content),
  revealPath: (filePath) => ipcRenderer.invoke("zenith:reveal-path", filePath),
  copyText: (text) => ipcRenderer.invoke("zenith:copy-text", text),
  getTerminalProfiles: () => ipcRenderer.invoke("zenith:terminal-profiles"),
  createTerminal: (profileId) => ipcRenderer.invoke("zenith:terminal-create", profileId),
  terminalInput: (id, data) => ipcRenderer.invoke("zenith:terminal-input", id, data),
  terminalResize: (id, cols, rows) => ipcRenderer.invoke("zenith:terminal-resize", id, cols, rows),
  killTerminal: (id) => ipcRenderer.invoke("zenith:terminal-kill", id),
  git: {
    getVersion: () => ipcRenderer.invoke("zenith:git-version"),
    getStatus: () => ipcRenderer.invoke("zenith:git-status"),
    stage: (paths) => ipcRenderer.invoke("zenith:git-stage", paths),
    unstage: (paths) => ipcRenderer.invoke("zenith:git-unstage", paths),
    stageAll: () => ipcRenderer.invoke("zenith:git-stage-all"),
    unstageAll: () => ipcRenderer.invoke("zenith:git-unstage-all"),
    commit: (message) => ipcRenderer.invoke("zenith:git-commit", message),
    fetch: () => ipcRenderer.invoke("zenith:git-fetch"),
    pull: () => ipcRenderer.invoke("zenith:git-pull"),
    push: () => ipcRenderer.invoke("zenith:git-push"),
    listBranches: () => ipcRenderer.invoke("zenith:git-branches"),
    checkoutBranch: (name) => ipcRenderer.invoke("zenith:git-checkout-branch", name),
    createBranch: (name) => ipcRenderer.invoke("zenith:git-create-branch", name),
    getRemotes: () => ipcRenderer.invoke("zenith:git-remotes"),
    getHistory: (limit, skip) => ipcRenderer.invoke("zenith:git-history", limit, skip),
    init: () => ipcRenderer.invoke("zenith:git-init"),
    onStatusChanged: (listener) => { const handler = () => listener(); ipcRenderer.on("zenith:git-status-changed", handler); return () => ipcRenderer.removeListener("zenith:git-status-changed", handler); },
  },
  auth: {
    getState: () => ipcRenderer.invoke("zenith:auth-get-state"),
    startGitHubSignIn: () => ipcRenderer.invoke("zenith:auth-github-start"),
    cancelGitHubSignIn: () => ipcRenderer.invoke("zenith:auth-github-cancel"),
    signOut: (provider) => ipcRenderer.invoke("zenith:auth-sign-out", provider),
    onChanged: (listener) => { const handler = (_event, state) => listener(state); ipcRenderer.on("zenith:auth-changed", handler); return () => ipcRenderer.removeListener("zenith:auth-changed", handler); },
  },
  github: {
    getCurrentUser: () => ipcRenderer.invoke("zenith:github-user"),
    getRepositoryFromCurrentWorkspace: () => ipcRenderer.invoke("zenith:github-repository-from-workspace"),
    listRepositories: (options) => ipcRenderer.invoke("zenith:github-list-repositories", options),
    selectCloneDestination: () => ipcRenderer.invoke("zenith:github-select-clone-destination"),
    cloneRepository: (options) => ipcRenderer.invoke("zenith:github-clone", options),
    cancelClone: () => ipcRenderer.invoke("zenith:github-clone-cancel"),
    openClonedWorkspace: (path) => ipcRenderer.invoke("zenith:github-open-cloned-workspace", path),
    createRepository: (options) => ipcRenderer.invoke("zenith:github-create-repository", options),
    publishCurrentWorkspace: (options) => ipcRenderer.invoke("zenith:github-publish", options),
    openExternal: (url) => ipcRenderer.invoke("zenith:github-open-external", url),
    onProgress: (listener) => { const handler = (_event, progress) => listener(progress); ipcRenderer.on("zenith:github-progress", handler); return () => ipcRenderer.removeListener("zenith:github-progress", handler); },
  },
  workspaceIndex: {
    getState: () => ipcRenderer.invoke("zenith:index-state"),
    findFiles: (query, options) => ipcRenderer.invoke("zenith:index-find-files", query, options),
    rebuild: () => ipcRenderer.invoke("zenith:index-rebuild"),
    onChanged: (listener) => { const handler = (_event, state) => listener(state); ipcRenderer.on("zenith:index-changed", handler); return () => ipcRenderer.removeListener("zenith:index-changed", handler); },
  },
  search: {
    files: (options) => ipcRenderer.invoke("zenith:search-files", options),
    text: (options) => ipcRenderer.invoke("zenith:search-text", options),
    cancel: (searchId) => ipcRenderer.invoke("zenith:search-cancel", searchId),
    onProgress: (listener) => { const handler = (_event, progress) => listener(progress); ipcRenderer.on("zenith:search-progress", handler); return () => ipcRenderer.removeListener("zenith:search-progress", handler); },
  },
  minimizeWindow: () => ipcRenderer.invoke("zenith:window-minimize"),
  toggleMaximizeWindow: () => ipcRenderer.invoke("zenith:window-toggle-maximize"),
  closeWindow: () => ipcRenderer.invoke("zenith:window-close"),
  onTerminalData: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("zenith:terminal-data", handler); return () => ipcRenderer.removeListener("zenith:terminal-data", handler); },
  onTerminalExit: (listener) => { const handler = (_event, payload) => listener(payload); ipcRenderer.on("zenith:terminal-exit", handler); return () => ipcRenderer.removeListener("zenith:terminal-exit", handler); },
});



