import { Copy, Maximize2, Plus, TerminalSquare, Trash2, X } from "lucide-react";
import { useState } from "react";

export default function Terminal({ height }: { height: number }) {
  const [command, setCommand] = useState(""); const [lines, setLines] = useState<string[]>([]); const [sessions, setSessions] = useState(1); const [minimized, setMinimized] = useState(false); const [maximized, setMaximized] = useState(false);
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!command.trim()) return; setLines((current) => [...current, `zenith@lunaris ~/Projects/lunaris $ ${command}`, "Command queued — terminal runtime will execute it in the desktop build."]); setCommand(""); };
  const copy = async () => { try { await navigator.clipboard.writeText(lines.join("\n")); } catch { /* clipboard access is optional in browser previews */ } };
  const currentHeight = minimized ? 43 : maximized ? 430 : height;
  return <section className="terminal-panel" style={{ height: currentHeight }}><header className="terminal-header"><div className="terminal-title"><TerminalSquare size={17} /><strong>Terminal {sessions > 1 ? `${sessions}` : ""}</strong><span>⌄</span></div><div className="terminal-actions"><button title="New terminal" onClick={() => setSessions((count) => count + 1)}><Plus size={16} /></button><button className="shell-select" onClick={() => setLines((current) => [...current, "Shell: bash"])}><span className="online-dot" />bash <span>⌄</span></button><button title="Copy output" onClick={() => void copy()}><Copy size={16} /></button><button title="Clear terminal" onClick={() => setLines([])}><Trash2 size={16} /></button><button title="Maximize terminal" onClick={() => setMaximized((value) => !value)}><Maximize2 size={16} /></button><button title="Minimize terminal" onClick={() => setMinimized((value) => !value)}><X size={17} /></button></div></header>{!minimized && <><form className="terminal-body" onSubmit={submit}>{lines.map((line, index) => <p key={index}>{line}</p>)}<label><span>zenith@lunaris</span><b> ~/Projects/lunaris</b> $ <input value={command} onChange={(event) => setCommand(event.target.value)} autoFocus /></label></form><div className="terminal-orb" /></>}</section>;
}
