import { BookOpen, Cloud, GitFork, KeyRound, LifeBuoy, Mail, ShieldAlert } from "lucide-react";
import Dialog from "./Dialog";
import { useUiStore } from "./uiStore";
import zenithMark from "../../assets/logo/zenith-mark-transparent.png";

export default function ZenithDialogs() {
  const { dialog, closeDialog, openDialog } = useUiStore();
  if (!dialog) return null;
  if (dialog.name === "auth") {
    const mode = dialog.mode === "forgot" ? "forgot" : dialog.mode === "signup" ? "signup" : "signin";
    const title = mode === "forgot" ? "Recover your Zenith account" : mode === "signup" ? "Create a Zenith account" : "Sign in to Zenith";
    return <Dialog title={title} subtitle="Account services are not connected in this desktop preview." onClose={closeDialog} size="small"><div className="service-dialog"><div className="service-icon"><KeyRound size={22} /></div><p>These screens are ready for a future secure account connection. Zenith will never store a password locally.</p>{mode !== "forgot" && <><label>Email<input placeholder="you@example.com" type="email" disabled /></label><label>Password<input placeholder="Available when account service is connected" type="password" disabled /></label></>}<button className="primary-dialog-action" disabled>{mode === "forgot" ? "Send recovery link" : mode === "signup" ? "Create account" : "Sign in"}</button><div className="dialog-links">{mode !== "signin" && <button onClick={() => openDialog("auth", "signin")}>Sign in instead</button>}{mode !== "signup" && <button onClick={() => openDialog("auth", "signup")}>Create account</button>}{mode !== "forgot" && <button onClick={() => openDialog("auth", "forgot")}>Forgot password?</button>}</div></div></Dialog>;
  }
  if (dialog.name === "github") return <Dialog title="Connect GitHub" subtitle="Repository connection is prepared, but OAuth is not configured yet." onClose={closeDialog} size="small"><div className="service-dialog"><div className="service-icon github-icon"><GitFork size={24} /></div><p>Connect a GitHub account to later browse repositories, clone projects, and create pull requests from Zenith.</p><button className="primary-dialog-action" disabled><GitFork size={16} />Continue with GitHub</button><small className="honest-note">No GitHub credentials, tokens, or repositories are requested by this preview.</small></div></Dialog>;
  if (dialog.name === "repository") {
    const mode = dialog.mode ?? "clone";
    const copy = mode === "clone" ? ["Clone Repository", "Paste a GitHub or Git URL", "Clone repository"] : mode === "initialize" ? ["Initialize Repository", "Create a Git repository in the open workspace", "Initialize repository"] : ["Open Repository", "Select an existing local repository", "Open repository"];
    return <Dialog title={copy[0]} subtitle="Git operations are not connected in this UI-only phase." onClose={closeDialog} size="small"><div className="service-dialog"><div className="service-icon"><Cloud size={22} /></div><p>{copy[1]}. The controls are displayed honestly until Zenith’s Git service is connected.</p>{mode === "clone" && <label>Repository URL<input placeholder="https://github.com/owner/repository.git" disabled /></label>}<button className="primary-dialog-action" disabled>{copy[2]}</button><small className="honest-note">Your workspace files will not be changed.</small></div></Dialog>;
  }
  if (dialog.name === "shortcuts") return <Dialog title="Keyboard Shortcuts" subtitle="Core local commands available in Zenith" onClose={closeDialog}><div className="shortcut-list"><p><span>Command Palette</span><kbd>Ctrl K</kbd></p><p><span>Save active file</span><kbd>Ctrl S</kbd></p><p><span>Open Settings</span><kbd>Ctrl ,</kbd></p><p><span>Toggle Explorer</span><kbd>Ctrl Shift E</kbd></p><p><span>Toggle terminal</span><kbd>Ctrl `</kbd></p></div></Dialog>;
  if (dialog.name === "help") return <Dialog title="Zenith Help" subtitle="A calm workspace for building on your computer" onClose={closeDialog}><div className="help-grid"><button onClick={() => openDialog("shortcuts")}><KeyRound size={18} /><span><strong>Keyboard shortcuts</strong><small>Browse the available local commands.</small></span></button><button onClick={() => openDialog("about")}><BookOpen size={18} /><span><strong>About Zenith</strong><small>Product and desktop information.</small></span></button><button disabled><LifeBuoy size={18} /><span><strong>Get support</strong><small>Support will be available with online services.</small></span></button></div></Dialog>;
  return <Dialog title="About Zenith" subtitle="Code · Create · Elevate" onClose={closeDialog} size="small"><div className="service-dialog"><div className="service-icon zenith-about-mark"><Mail aria-hidden="true" /><img src={zenithMark} alt="Zenith" /></div><p>Zenith is a local-first desktop development workspace with files, tabs, Monaco editing, and terminal sessions running on your computer.</p><small className="honest-note"><ShieldAlert size={13} />No cloud account is connected.</small></div></Dialog>;
}

